/*
Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
This software is licensed under the MIT License.
File: /Users/martinbechard/dev/mcp-dev-prompter/src/index.ts
This was generated by Claude Sonnet 3.5, with the assistance of my human mentor

Main entry point for the Dev Prompter MCP Server
Where all exports come together!
*/

// Core exports
export { DevPrompterServer } from "./DevPrompterServer.js";
export { parseArgs, type ServerArgs } from "./StdioServer.js";
export { Logger } from "./Logger.js";

// Template types and configuration
export type {
  TemplateMetadata,
  TemplateArgument,
  LoadedTemplate,
  PromptConfig,
} from "./PromptConfig.js";

// Constants and validation
export { PromptValidator } from "./PromptValidator.js";
export {
  TEMPLATE_CONSTANTS,
  SYSTEM_CONSTANTS,
  type TemplateConstants,
  type SystemConstants,
} from "./Constants.js";

// Type exports from PromptTypes
export type {
  PromptTemplate,
  PromptRequest,
  PromptResponse,
  PromptContext,
} from "./PromptTypes.js";
