/*
Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
This software is licensed under the MIT License.
File: /Users/martinbechard/dev/mcp-dev-prompter/src/PromptConfig.ts
This was generated by Claude Sonnet 3.5, with the assistance of my human mentor

Type definitions for prompt template configuration
Where templates meet their metadata match!
*/

/**
 * Metadata configuration for a prompt template
 */
export type TemplateMetadata = {
  /** Human-readable description of the prompt */
  description: string;

  /** Semantic version of the template */
  version: string;

  /** Arguments that can be used in the template */
  arguments: TemplateArgument[];
};

/**
 * Specification for a template argument
 */
export type TemplateArgument = {
  /** Name of the argument for use in template */
  name: string;

  /** Human-readable description of the argument */
  description: string;

  /** Whether this argument must be provided */
  required: boolean;
};

/**
 * Fully loaded and parsed template
 */
export type LoadedTemplate = {
  /** Base filename without extension */
  id: string;

  /** Template metadata from frontmatter */
  metadata: TemplateMetadata;

  /** Parsed template sections */
  sections: {
    /** User-visible description */
    description: string;

    /** Handlebars template content */
    template: string;
  };

  /** Raw template content */
  rawContent: string;
};

/**
 * Configuration for prompt generation
 */
export type PromptConfig = {
  /** Template identifier (filename without extension) */
  templateId: string;

  /**
   * Template argument values
   * Keys must match argument names in template
   */
  arguments: Record<string, unknown>;
};
